name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: bug
body:
  - type: textarea
    attributes:
      label: Description
      description: "A clear and concise description of what the bug is."
      placeholder: "Describe the issue you encountered."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: "Steps to reproduce the behavior"
      placeholder: "1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots to help explain your problem."
      placeholder: "Attach screenshots here if they would be helpful in understanding the issue."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Information
      description: "Add any other context about the problem here."
      placeholder: "Any additional details that might help understand the issue."
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Version
      description: Does this issue exist on the current version?
      options:
        - label: I've confirmed the issue exists on the latest version
          required: true
