name: Feature request
description: Suggest an idea for this project
title: "[Request]: "
labels: request
body:
- type: textarea
  attributes:
    label: Request
    description: "Describe the what you'd like to see added"
    placeholder: "A clear and concise description of what you want to happen."
  validations:
    required: true
